---

#######################################
### ORGANIZATION VARS
#######################################

### UBUNTU

# foreman_organization_ubuntu: "{{ foreman_organization }}"

# foreman_organization_ubuntu2004: "{{ foreman_organization_ubuntu }}"
# foreman_organization_ubuntu2204: "{{ foreman_organization_ubuntu }}"
# foreman_organization_ubuntu2404: "{{ foreman_organization_ubuntu }}"
